name: Test and Build

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write
  checks: read

jobs:
  build:
    name: Feeds Package Test Build
    uses: openwrt/actions-shared-workflows/.github/workflows/multi-arch-test-build.yml@main
    with:
      matrix: >-
        {"include":[
          {"arch":"aarch64_cortex-a53","target":"mediatek-mt7622","runtime_test":false},
          {"arch":"aarch64_generic","target":"armsr-armv8","runtime_test":true},
          {"arch":"arm_cortex-a15_neon-vfpv4","target":"armsr-armv7","runtime_test":true},
          {"arch":"arm_cortex-a9_vfpv3-d16","target":"mvebu-cortexa9","runtime_test":false},
          {"arch":"i386_pentium-mmx","target":"x86-geode","runtime_test":true},
          {"arch":"mips_24kc","target":"ath79-generic","runtime_test":true},
          {"arch":"mipsel_24kc","target":"mt7621","runtime_test":false},
          {"arch":"powerpc_464fp","target":"apm821xx-nand","runtime_test":false},
          {"arch":"powerpc_8548","target":"mpc85xx-p1010","runtime_test":false},
          {"arch":"riscv64_generic","target":"sifiveu-generic","runtime_test":false},
          {"arch":"x86_64","target":"x86-64","runtime_test":true}
        ]}
